# Generated by Django 4.2.4 on 2026-01-27 23:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120, verbose_name='Nome de exibição')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('city', models.CharField(default='Araraquara', max_length=80, verbose_name='Cidade')),
                ('region', models.CharField(blank=True, default='Araraquara e região', max_length=120, verbose_name='Região de atendimento')),
                ('is_caregiver', models.BooleanField(default=True, verbose_name='É cuidador(a)?')),
                ('bio', models.TextField(blank=True, help_text='Descreva sua experiência e qualificações', verbose_name='Biografia')),
                ('services', models.CharField(blank=True, help_text='Ex: banho, companhia, medicação, curativos', max_length=255, verbose_name='Serviços oferecidos')),
                ('phone_whatsapp', models.CharField(help_text='Somente números com DDD (ex: 16999998888)', max_length=20, validators=[django.core.validators.RegexValidator(message='Telefone deve conter 10 ou 11 dígitos (DDD + número)', regex='^\\d{10,11}$')], verbose_name='WhatsApp')),
                ('available', models.BooleanField(default=True, help_text='Está aceitando novos clientes?', verbose_name='Disponível')),
                ('published', models.BooleanField(default=False, help_text='Marque para aparecer publicamente', verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil Profissional',
                'verbose_name_plural': 'Perfis Profissionais',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['-updated_at'], name='profiles_pr_updated_8c7319_idx'), models.Index(fields=['published', 'available'], name='profiles_pr_publish_3eac7f_idx')],
            },
        ),
    ]
