# Generated by Django 4.2.4 on 2026-01-27 23:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome completo do interessado', max_length=120, verbose_name='Nome')),
                ('phone', models.CharField(blank=True, help_text='Telefone com DDD (opcional)', max_length=30, validators=[django.core.validators.RegexValidator(message='Telefone deve conter 10 ou 11 dígitos', regex='^\\d{10,11}$')], verbose_name='Telefone')),
                ('message', models.TextField(help_text='Descrição da necessidade ou interesse', verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('contacted', models.BooleanField(default=False, help_text='Marque quando entrar em contato com este lead', verbose_name='Contatado?')),
                ('notes', models.TextField(blank=True, help_text='Anotações sobre contato e acompanhamento', verbose_name='Observações internas')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='profiles.professionalprofile', verbose_name='Perfil profissional')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='public_lead_created_5c7b97_idx'), models.Index(fields=['profile', '-created_at'], name='public_lead_profile_6f0064_idx'), models.Index(fields=['contacted'], name='public_lead_contact_d796d5_idx')],
            },
        ),
    ]
